<Project>
  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="14.7.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <NswagFileExists Condition="Exists('$(MSBuildProjectDirectory)\.nswag')">true</NswagFileExists>
  </PropertyGroup>
  <Target
    Name="NSwag"
    AfterTargets="PostBuildEvent"
    Condition="'$(Configuration)' == 'Debug' And '$(NswagFileExists)' == 'true'"
  >
    <Message Text="*** Running NSwag builder..." Importance="high" />
    <Exec
      WorkingDirectory="$(MSBuildProjectDirectory)"
      Command="$(NSwagExe_Net100) run .nswag /variables:Configuration=$(Configuration),msBuildOutputPath=$(OutputPath)"
    />
  </Target>
  <Import Project="Build.GitVersion.props" />
</Project>
