<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PingPong.ActorSystem\PingPong.ActorSystem.csproj" />
    <ProjectReference Include="..\..\src\PingPong.Game\PingPong.Game.csproj" />
  </ItemGroup>

</Project>
