export const CURRENT_TIME_REFRESH_INTERVAL_MS = 30_000;
export const CHARACTER_REACTION_DURATION_MS = 620;
export const PAGE_INTRO_GUIDE_DELAY_MS = 350;
export const REWARD_REVEAL_DELAY_MS = 250;
export const FOLLOW_UP_REWARD_REVEAL_DELAY_MS = 50;
export const PAYOUT_CELEBRATION_DURATION_MS = 3_300;
